language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - python test_random_dice.py
  - coverage run test_random_dice.py

after_success:
  - coveralls




